name: flag-service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "flag-service/**"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/_ci-python.yml"
  pull_request:
    paths:
      - "flag-service/**"

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/_ci-python.yml
    with:
      service: flag-service
    secrets: inherit
